# Application for Azure SQL Service
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-azuresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/microsoft/mssql-docker/tree/master/linux/sample-helm-chart
    targetRevision: main
    path: deploy/azuresql
  destination:
    server: https://kubernetes.default.svc
    namespace: sql
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions: